name: Lint, Type Check and Deploy

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - '**'

jobs:
  lint:
    name: Lint and Type Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22' # Мы подняли версию до 22, чтобы не было ошибки с sqlite
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint

      - name: Run type check
        run: npm run type-check

      - name: Check formatting
        run: npx prettier --check "src/**/*.ts"

  deploy:
    name: Deploy to Cloudflare
    needs: lint # Это заставляет деплой запускаться ТОЛЬКО если проверка кода прошла успешно
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: deploy
